include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/core/ffi/**
    - lib/core/ffi.disabled/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - avoid_print
    - prefer_single_quotes
    - sort_constructors_first
    - unawaited_futures
