// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypto.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  RustLib._();
  @internal
  static final instance = RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 560517733;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'selona_rust',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  String crateApiCryptoDecodeFromPnk(
      {required String inputPath, required String outputDir});

  List<String> crateApiCryptoDecodeFromPnkAuto(
      {required String inputPath, required String outputDir});

  Uint8List crateApiCryptoDecodeToBytes({required String inputPath});

  void crateApiCryptoDeleteTempDir({required String path});

  void crateApiCryptoDeleteTempFile({required String path});

  void crateApiCryptoEncodeToPnk(
      {required String inputPath,
      required String outputPath,
      required String passphrase});

  String crateApiCryptoHashPassphrase({required String passphrase});

  String crateApiCryptoHashPin({required String pin});

  bool crateApiCryptoVerifyPassphrase(
      {required String passphrase, required String hash});

  bool crateApiCryptoVerifyPin({required String pin, required String hash});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiCryptoDecodeFromPnk(
      {required String inputPath, required String outputDir}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(inputPath);
        final arg1 = cst_encode_String(outputDir);
        return wire.wire__crate__api__crypto__decode_from_pnk(arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiCryptoDecodeFromPnkConstMeta,
      argValues: [inputPath, outputDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoDecodeFromPnkConstMeta =>
      const TaskConstMeta(
        debugName: 'decode_from_pnk',
        argNames: ['inputPath', 'outputDir'],
      );

  @override
  List<String> crateApiCryptoDecodeFromPnkAuto(
      {required String inputPath, required String outputDir}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(inputPath);
        final arg1 = cst_encode_String(outputDir);
        return wire.wire__crate__api__crypto__decode_from_pnk_auto(arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_String,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiCryptoDecodeFromPnkAutoConstMeta,
      argValues: [inputPath, outputDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoDecodeFromPnkAutoConstMeta =>
      const TaskConstMeta(
        debugName: 'decode_from_pnk_auto',
        argNames: ['inputPath', 'outputDir'],
      );

  @override
  Uint8List crateApiCryptoDecodeToBytes({required String inputPath}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(inputPath);
        return wire.wire__crate__api__crypto__decode_to_bytes(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_prim_u_8_strict,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiCryptoDecodeToBytesConstMeta,
      argValues: [inputPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoDecodeToBytesConstMeta =>
      const TaskConstMeta(
        debugName: 'decode_to_bytes',
        argNames: ['inputPath'],
      );

  @override
  void crateApiCryptoDeleteTempDir({required String path}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(path);
        return wire.wire__crate__api__crypto__delete_temp_dir(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiCryptoDeleteTempDirConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoDeleteTempDirConstMeta =>
      const TaskConstMeta(
        debugName: 'delete_temp_dir',
        argNames: ['path'],
      );

  @override
  void crateApiCryptoDeleteTempFile({required String path}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(path);
        return wire.wire__crate__api__crypto__delete_temp_file(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiCryptoDeleteTempFileConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoDeleteTempFileConstMeta =>
      const TaskConstMeta(
        debugName: 'delete_temp_file',
        argNames: ['path'],
      );

  @override
  void crateApiCryptoEncodeToPnk(
      {required String inputPath,
      required String outputPath,
      required String passphrase}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(inputPath);
        final arg1 = cst_encode_String(outputPath);
        final arg2 = cst_encode_String(passphrase);
        return wire.wire__crate__api__crypto__encode_to_pnk(arg0, arg1, arg2);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiCryptoEncodeToPnkConstMeta,
      argValues: [inputPath, outputPath, passphrase],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoEncodeToPnkConstMeta => const TaskConstMeta(
        debugName: 'encode_to_pnk',
        argNames: ['inputPath', 'outputPath', 'passphrase'],
      );

  @override
  String crateApiCryptoHashPassphrase({required String passphrase}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(passphrase);
        return wire.wire__crate__api__crypto__hash_passphrase(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoHashPassphraseConstMeta,
      argValues: [passphrase],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoHashPassphraseConstMeta =>
      const TaskConstMeta(
        debugName: 'hash_passphrase',
        argNames: ['passphrase'],
      );

  @override
  String crateApiCryptoHashPin({required String pin}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(pin);
        return wire.wire__crate__api__crypto__hash_pin(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoHashPinConstMeta,
      argValues: [pin],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoHashPinConstMeta => const TaskConstMeta(
        debugName: 'hash_pin',
        argNames: ['pin'],
      );

  @override
  bool crateApiCryptoVerifyPassphrase(
      {required String passphrase, required String hash}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(passphrase);
        final arg1 = cst_encode_String(hash);
        return wire.wire__crate__api__crypto__verify_passphrase(arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoVerifyPassphraseConstMeta,
      argValues: [passphrase, hash],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoVerifyPassphraseConstMeta =>
      const TaskConstMeta(
        debugName: 'verify_passphrase',
        argNames: ['passphrase', 'hash'],
      );

  @override
  bool crateApiCryptoVerifyPin({required String pin, required String hash}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(pin);
        final arg1 = cst_encode_String(hash);
        return wire.wire__crate__api__crypto__verify_pin(arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoVerifyPinConstMeta,
      argValues: [pin, hash],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoVerifyPinConstMeta => const TaskConstMeta(
        debugName: 'verify_pin',
        argNames: ['pin', 'hash'],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
